// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameStaff = "staff"

// Staff mapped from table <staff>
type Staff struct {
	Kode		string         `gorm:"column:Kode;primaryKey" json:"kode"`
	Nama        string         `gorm:"column:NamaLengkap;not null" json:"nama"`
	Email    	string         `gorm:"column:Email;not null" json:"email"`
	Password    string         `gorm:"column:password;not null" json:"-"`
}

// TableName Staff's table name
func (*Staff) TableName() string {
	return TableNameStaff
}
